# Generated by Django 2.0.5 on 2018-08-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook_app', '0007_auto_20180509_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
